bbricks/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('editprofile/', views.user_profile),
    path('login/', views.login),
    path('auth/', views.auth_view),
    path('logout/', views.logout),
    path('loggedin/', views.loggedin),
    path('invalid/', views.invalid_login),
    path('register/', views.register_user),
    path('register_success/', views.register_success),
    url(r'^profile/(?P<username>\w+)/$', views.profile),
    url(r'^all/$', views.properties),
    url(r'^create/$', views.create),
    url(r'^get_apartment/(?P<apartment_id>\d+)/$', views.apartment),
    url(r'^get_house/(?P<house_id>\d+)/$', views.house),
    url(r'^get_land/(?P<land_id>\d+)/$', views.land),
    url(r'^create_apartment/$', views.create_apartment),
    url(r'^create_house/$', views.create_house),
    url(r'^create_land/$', views.create_land),
    url(r'^sell/(?P<property_id>\d+)/$', views.sell),
    url(r'^rent/(?P<property_id>\d+)/$', views.rent),
    url(r'^pg/(?P<property_id>\d+)/$', views.pg),
    url(r'^buy/$', views.buy),
    url(r'^buy_rent/$', views.buy_rent),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('bbricks/', include('bbricks.urls')),
    path('admin/', admin.site.urls),
]

bbricks/models.py
from django.db import models
from django.contrib.auth.models import User
from time import time
from django.template.defaultfilters import slugify


class State(models.Model):
    state_name = models.CharField(max_length=200)

    def __str__(self):
        return self.state_name


class City(models.Model):
    city_name = models.CharField(max_length=200)
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    def __str__(self):
        return self.city_name


def get_upload_file_name(instance, filename):
    return "uploaded_files/%s_%s" % (str(time()).replace('.', '_'), filename)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.FileField(upload_to=get_upload_file_name)
    mobile_no = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class Property(models.Model):
    seller = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    type = models.CharField(max_length=50, choices=[('Apartment', 'Apartment'), ('Land', 'Land'),
                                                    ('Independent House', 'Independent House')])
    posted_for = models.CharField(max_length=50, choices=[('Sale', 'Sale'), ('Rent', 'Rent'),
                                                          ('Paying Guest', 'Paying Guest')])
    posted_by = models.CharField(max_length=10, choices=[('Owner', 'Owner'), ('Dealer', 'Dealer'),
                                                         ('Builder', 'Builder')])
    project_name = models.CharField(max_length=50)
    locality = models.CharField(max_length=50)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    address = models.CharField(max_length=200)
    area = models.IntegerField()
    units = models.CharField(max_length=50, choices=[('Marla', 'Marla'), ('Acres', 'Acres'), ('Sq.Ft.', 'Sq.Ft.')])
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.project_name


class Residential(Property):
    bedrooms = models.IntegerField()
    balconies = models.IntegerField()
    total_floors = models.IntegerField()
    age = models.IntegerField()
    parking = models.BooleanField()
    lift = models.BooleanField()
    park = models.BooleanField()
    power_backup = models.CharField(max_length=50, choices=[('None', 'None'), ('Full', 'Full'), ('Partial', 'Partial')])

    class Meta:
        abstract = True


class Apartment(Residential):
    property_on_floor = models.IntegerField()
    fire_alarm = models.BooleanField()

    def __str__(self):
        return self.project_name


class Villa(Residential):
    water_source = models.CharField(max_length=50, choices=[('Borewell/Tank', 'Borewell/Tank'),
                                                            ('Municipal Corporation', 'Municipal Corporation')])
    overlooking = models.CharField(max_length=50, choices=[('Main Road', 'Main Road'), ('Park', 'Park'),
                                                           ('Club', 'Club')], blank=True, null=True)

    def __str__(self):
        return self.project_name


class Land(Property):
    length = models.IntegerField()
    breadth = models.IntegerField()
    floors_allowed = models.IntegerField()
    registered = models.BooleanField()
    price_per_merla = models.IntegerField()
    boundary_wall = models.BooleanField()
    overlooking = models.CharField(max_length=50, choices=[('Main Road', 'Main Road'), ('Park', 'Park'),
                                                           ('Club', 'Club')], blank=True, null=True)

    def __str__(self):
        return self.project_name


class Sell(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    price = models.IntegerField()

    def __str__(self):
        return self.property.project_name


class Rent(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    rent_to = models.CharField(max_length=50, choices=[('Family', 'Family'), ('Single Men', 'Single Men'),
                                                       ('Single Women', 'Single Women')])
    available_from = models.DateField()
    furnishing = models.CharField(max_length=50, choices=[('Fully furnished', 'Fully furnished'),
                                                          ('Semi furnished', 'Semi furnished'),
                                                          ('Unfurnished', 'Unfurnished')])
    rent = models.IntegerField()
    security_deposit = models.IntegerField()

    def __str__(self):
        return self.property.project_name


class PayingGuest(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    available_for = models.CharField(max_length=50, choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Both', 'Both')])
    suitable_for = models.CharField(max_length=50, choices=[('Students', 'Students'), ('Professionals', 'Professionals')])
    available_from = models.DateField()
    furnishing = models.CharField(max_length=50, choices=[('Fully furnished', 'Fully furnished'),
                                                          ('Semi furnished', 'Semi furnished'),
                                                          ('Unfurnished', 'Unfurnished')])
    rent = models.IntegerField()
    security_deposit = models.IntegerField()

    def __str__(self):
        return self.property.project_name


def get_image_filename(instance, filename):
    title = instance.property.project_name
    slug = slugify(title)
    return "uploaded_files/%s-%s" % (slug, filename)


class Images(models.Model):
    property = models.ForeignKey(Property, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name='Image')

bbricks/views.py
from django.shortcuts import render_to_response, render
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.template.context_processors import csrf
from .forms import MyRegistrationForm, UserProfileForm, ImageForm, ApartmentForm, \
    SellForm, RentForm, PGForm, HouseForm, LandForm
from .models import UserProfile, Apartment, Images, Property, Sell, Rent, PayingGuest, Villa, Land
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms import modelformset_factory


def home(request):
    return render_to_response('bbricks/home.html')


def login(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('bbricks/login.html', c)


def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)

        try:
            check = UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            check = None

        if check is not None:
            return HttpResponseRedirect('/bbricks/loggedin')
        else:
            return HttpResponseRedirect('/bbricks/editprofile')
    else:
        return HttpResponseRedirect('/bbricks/invalid')


@login_required
def loggedin(request):
    return render_to_response('bbricks/loggedin.html',
                              {'user': request.user,
                               'properties': request.user.userprofile.property_set.all()})


def invalid_login(request):
    return render_to_response('bbricks/invalid_login.html')


def logout(request):
    auth.logout(request)
    return render_to_response('bbricks/logout.html')


def register_user(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/bbricks/register_success')

    args = {}
    args.update(csrf(request))

    args['form'] = MyRegistrationForm()

    return render_to_response('bbricks/register.html', args)


def register_success(request):
    return render_to_response('bbricks/register_success.html')


@login_required
def user_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/bbricks/loggedin')
    else:
        user = request.user
        profile = user.profile
        form = UserProfileForm(instance=profile)

    args = {}
    args.update(csrf(request))

    args['form'] = form

    return render_to_response('bbricks/edit_profile.html', args)


def profile(request, username):
    user = User.objects.get(username=username)
    return render_to_response('bbricks/profile.html', {'user': user,
                                                       'properties': user.userprofile.property_set.all()})


def apartment(request, apartment_id=1):
    a = Apartment.objects.get(id=apartment_id)
    p = None
    if a.posted_for.__eq__('Sale'):
        p = Sell.objects.get(property=Property.objects.get(id=a.id))
    if a.posted_for.__eq__('Rent'):
        p = Rent.objects.get(property=Property.objects.get(id=a.id))
    if a.posted_for.__eq__('Paying Guest'):
        p = PayingGuest.objects.get(property=Property.objects.get(id=a.id))
    return render(request, 'bbricks/apartment.html',
                  {'apartment': a,
                   'p': p})


def house(request, house_id=1):
    h = Villa.objects.get(id=house_id)
    p = None
    if h.posted_for.__eq__('Sale'):
        p = Sell.objects.get(property=Property.objects.get(id=h.id))
    if h.posted_for.__eq__('Rent'):
        p = Rent.objects.get(property=Property.objects.get(id=h.id))
    if h.posted_for.__eq__('Paying Guest'):
        p = PayingGuest.objects.get(property=Property.objects.get(id=h.id))
    return render(request, 'bbricks/house.html',
                  {'house': h,
                   'p': p})


def land(request, land_id=1):
    l = Land.objects.get(id=land_id)
    p = Sell.objects.get(property=Property.objects.get(id=l.id))
    return render(request, 'bbricks/land.html',
                  {'land': l,
                   'p': p})


def create(request):
    if request.method == 'POST':
        t = request.POST.get('type')
        return HttpResponseRedirect('/bbricks/create_%s' % t)
    else:
        args = {}
        args.update(csrf(request))
        return render_to_response('bbricks/create.html', args)


@login_required
def create_apartment(request):
    ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=2)

    if request.POST:
        apartmentForm = ApartmentForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())

        if apartmentForm.is_valid() and formset.is_valid():
            apartment_form = apartmentForm.save(commit=False)
            apartment_form.seller = request.user.userprofile
            apartment_form.type = 'Apartment'
            apartment_form.save()

            for f in formset.cleaned_data:
                image = f['image']
                photo = Images(property=apartment_form, image=image)
                photo.save()

            if apartment_form.posted_for == 'Sale':
                return HttpResponseRedirect('/bbricks/sell/%s' % apartment_form.id)
            if apartment_form.posted_for == 'Rent':
                return HttpResponseRedirect('/bbricks/rent/%s' % apartment_form.id)
            if apartment_form.posted_for == 'Paying Guest':
                return HttpResponseRedirect('/bbricks/pg/%s' % apartment_form.id)
        else:
            print(apartmentForm.errors, formset.errors)
    else:
        apartmentForm = ApartmentForm()
        formset = ImageFormSet(queryset=Images.objects.none())

    args = {}
    args.update(csrf(request))
    args['apartmentForm'] = apartmentForm
    args['formset'] = formset

    return render_to_response('bbricks/create_apartment.html', args)


def create_house(request):
    ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=2)

    if request.POST:
        houseForm = HouseForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())

        if houseForm.is_valid() and formset.is_valid():
            house_form = houseForm.save(commit=False)
            house_form.seller = request.user.userprofile
            house_form.type = 'Independent House'
            house_form.save()

            for f in formset.cleaned_data:
                image = f['image']
                photo = Images(property=house_form, image=image)
                photo.save()

            if house_form.posted_for == 'Sale':
                return HttpResponseRedirect('/bbricks/sell/%s' % house_form.id)
            if house_form.posted_for == 'Rent':
                return HttpResponseRedirect('/bbricks/rent/%s' % house_form.id)
            if house_form.posted_for == 'Paying Guest':
                return HttpResponseRedirect('/bbricks/pg/%s' % house_form.id)
        else:
            print(houseForm.errors, formset.errors)
    else:
        houseForm = HouseForm()
        formset = ImageFormSet(queryset=Images.objects.none())

    args = {}
    args.update(csrf(request))
    args['houseForm'] = houseForm
    args['formset'] = formset

    return render_to_response('bbricks/create_house.html', args)


def create_land(request):
    ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=2)

    if request.POST:
        landForm = LandForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())

        if landForm.is_valid() and formset.is_valid():
            land_form = landForm.save(commit=False)
            land_form.seller = request.user.userprofile
            land_form.type = 'Land'
            land_form.posted_for = 'Sale'
            land_form.save()

            for f in formset.cleaned_data:
                image = f['image']
                photo = Images(property=land_form, image=image)
                photo.save()

            return HttpResponseRedirect('/bbricks/sell/%s' % land_form.id)
        else:
            print(landForm.errors, formset.errors)
    else:
        landForm = LandForm()
        formset = ImageFormSet(queryset=Images.objects.none())

    args = {}
    args.update(csrf(request))
    args['landForm'] = landForm
    args['formset'] = formset

    return render_to_response('bbricks/create_land.html', args)


def sell(request, property_id):
    if property_id:
        p = Property.objects.get(id=property_id)
        if request.POST:
            form = SellForm(request.POST)
            if form.is_valid():
                s = form.save(commit=False)
                s.property = p
                s.save()

                if p.type.__eq__('Apartment'):
                    return HttpResponseRedirect('/bbricks/get_apartment/%s' % property_id)
                if p.type.__eq__('Independent House'):
                    return HttpResponseRedirect('/bbricks/get_house/%s' % property_id)
                if p.type.__eq__('Land'):
                    return HttpResponseRedirect('/bbricks/get_land/%s' % property_id)
        else:
            form = SellForm()

        args = {}
        args.update(csrf(request))
        args['form'] = form
        args['property'] = p
        return render_to_response('bbricks/sell.html', args)


def rent(request, property_id):
    if property_id:
        p = Property.objects.get(id=property_id)
        if request.POST:
            form = RentForm(request.POST)
            if form.is_valid():
                s = form.save(commit=False)

bbricks/templates/bbricks/all.html
{% extends 'bbricks/base.html' %}

{% block sidebar %}

    <ul>
        <li><a href="/bbricks/all">Properties</a></li>
        <li><a href="/bbricks/create">Create Property</a></li>
    </ul>


{% endblock %}

{% block content %}

<!--    <h2>Language is: {{ language }}</h2>

    <h2>Session Language is: {{ session_language }}</h2>
-->
    {% if properties.count > 0 %}
        <h1>Properties</h1>
        {% for property in properties %}
            <div>
                <h3>{{ property.description }}</h3>
                <h4>{{ property.posted_by }}: {{ property.seller.user.username }}</h4>
                <p>Address: {{ property.address }}</p>
                <p>Locality: {{ property.locality }}</p><br>
            </div>
        {% endfor %}
    {% endif %}


{% endblock %}

bbricks/templates/bbricks/apartment.html
{% extends 'bbricks/base.html' %}

{% block sidebar %}
        <a class="nav-link" href="/bbricks/loggedin/">Your Profile</a>
{% endblock %}

{% block content %}
<div id="view-property" class="col-lg-12 property-nodule jumbotron" >
    <h1>{{ apartment.posted_by }}: {{ apartment.seller.user.username }}</h1>
    <p>Address: <span class="location">{{ apartment.address }}</span></p>
    <p>Locality: {{ apartment.locality }}</p>
    <p>City: {{ apartment.city }}</p>
    <p>State: {{ apartment.state }}</p>
    <p>Area: {{ apartment.area }} {{ apartment.units }}</p>
    <p>Bedrooms: {{ apartment.bedrooms }}</p>
    <p>Age: {{ apartment.age }}</p>
    {% if apartment.posted_for == 'Sale' %}
        <p>Price: {{ p.price }}</p>
    {% endif %}
    {% if apartment.posted_for == 'Rent' %}
        <p>Rent: {{ p.rent }}</p>
    {% endif %}
    {% if apartment.posted_for == 'Paying Guest' %}
        <p>Rent: {{ p.rent }}</p>
    {% endif %}
    <p>Description: {{ apartment.description }}</p>
    <div class="map" id="map-canvas" style="width: 480px; height: 480px"></div><br>
    {% if apartment.images_set %}
        {% for image in apartment.images_set.all %}
            <p><img src="/static/assets/{{ image.image }}" width="200" /></p>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

bbricks/templates/bbricks/apartments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bbricks/templates/bbricks/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}My Base Template{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

    <style type="text/css">
        body { padding: 60px; }
    </style>

</head>

<body class="bg-light">

    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
      <a class="navbar-brand mr-auto mr-lg-0" href="/bbricks/loggedin/">Blooming Bricks</a>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          </li>

        </ul>
      </div>
    </nav>

    <div class="nav-scroller bg-white box-shadow">
      <nav class="nav nav-underline">
        <a class="nav-link active" href="/bbricks/loggedin">Dashboard</a>
        {% block sidebar %}
          {% endblock %}
      </nav>
    </div>



    <div class="container">
        {% block content %}

        {% endblock %}
    </div>




 <!--   <div id="page">
        <div id="sidebar">

                <ul>
                    <li><a href="/accounts/login/">Home</a></li>
                </ul>

        </div>

        <div id="content">

            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}



            <div class="clearfix"></div>
            <img src="{% static 'assets/images/python-logo.png' %}" width="200" />
        </div>
    </div>
-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script src="{% static 'assets/js/google_maps.js' %}"></script>
</body>
</html>

bbricks/templates/bbricks/create.html
{% extends 'bbricks/base.html' %}

{% block sidebar %}
    <a class="nav-link" href="/bbricks/loggedin">Cancel</a>
{% endblock %}

{% block content %}

    <form action="/bbricks/create/" method="post">{% csrf_token %}

        <label for="type">Property Type: </label>
        <select name="type" required id="type">
            <option value selected>---------</option>
            <option value="apartment">Apartment</option>
            <option value="house">Independent House</option>
            <option value="land">Land</option>
        </select>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

{% endblock %}

bbricks/templates/bbricks/create_land.html
{% extends 'bbricks/base.html' %}

{% block sidebar %}
            <a class="nav-link" href="/bbricks/loggedin/">Cancel</a>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-6 col-sm-6 col-lg-4">
    <form id="land_form" action="/bbricks/create_land/" method="post" enctype="multipart/form-data">{% csrf_token %}

        {% for hidden in landForm.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {{ landForm.as_ul }}

        {{ formset.management_form }}
        {% for form in formset %}
            {{ form }}
        {% endfor %}

        <input type="submit" value="Add Property" class="btn btn-primary"/>

    </form>
    </div>
</div>
{% endblock %}

bbricks/templates/bbricks/invalid_login.html
{% extends 'bbricks/base.html' %}

{% block content %}

    <h2>Your login details are invalid!</h2>
    <p>Click <a href="/bbricks/login/">here</a> to login again.</p>

{% endblock %}

bbricks/templates/bbricks/land.html
{% extends 'bbricks/base.html' %}

{% block sidebar %}
        <a class="nav-link" href="/bbricks/loggedin/">Your Profile</a>
{% endblock %}

{% block content %}
<div id="view-property" class="col-lg-12 property-nodule jumbotron" >
    <h1>{{ land.posted_by }}: {{ land.seller.user.username }}</h1>
    <p>Address: <span class="location">{{ land.address }}</span></p>
    <p>Locality: {{ land.locality }}</p>
    <p>City: {{ land.city }}</p>
    <p>State: {{ land.state }}</p>
    <p>Area: {{ land.area }} {{ land.units }}</p>
    <p>Length: {{ land.length }}</p>
    <p>Breadth: {{ land.breadth }}</p>
    <p>Price per marla: {{ land.price_per_merla }}</p>
    <p>Price: {{ p.price }}</p>
    <p>Description: {{ land.description }}</p>
    <div class="map" id="map-canvas" style="width: 480px; height: 480px"></div><br>
    {% if land.images_set %}
        {% for image in land.images_set.all %}
            <p><img src="/static/assets/{{ image.image }}" width="200" /></p>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

bbricks/templates/bbricks/loggedin.html
{% extends 'bbricks/base.html' %}

{% block sidebar %}

        <a class="nav-link" href="/bbricks/create/">Add property</a>
        <a class="nav-link" href="/bbricks/buy/">Buy property</a>
        <a class="nav-link" href="/bbricks/buy_rent/">Rent property</a>
        <a class="nav-link" href="/bbricks/editprofile/">Edit Profile</a>
        <a class="nav-link" href="/bbricks/logout/">Logout</a>

{% endblock %}

{% block content %}

    <h4>Hi {{ user.username }} you are now logged in!</h4>

    <p><img src="/static/assets/{{ user.userprofile.photo }}" width="200" /></p>
    <p>{{ user.first_name }} {{ user.last_name }}</p>

    {% if notifications.count > 0 %}
        <h3>Notifications</h3>
        {% for n in notifications %}
            <p><a href="/notification/show/{{ n.id }}">{{ n.title }}</a></p>
        {% endfor %}
    {% endif %}


    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h2 class="border-bottom border-gray pb-2 mb-0">Properties</h2>
 {% if properties.count > 0 %}
        {% for property in properties %}
        <div class="media text-muted pt-3">
          <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">

            <div>
                {% if property.type == 'Apartment' %}
                <h6><a href="/bbricks/get_apartment/{{ property.id }}/">{{ property.description }}</a></h6>
                {% endif %}
                {% if property.type == 'Independent House' %}
                <h6><a href="/bbricks/get_house/{{ property.id }}/">{{ property.description }}</a></h6>
                {% endif %}
                {% if property.type == 'Land' %}
                <h6><a href="/bbricks/get_land/{{ property.id }}/">{{ property.description }}</a></h6>
                {% endif %}
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <a href="/bbricks/profile/{{ user.username }}"><strong class="d-block text-gray-dark">@{{ user.username }}</strong></a>
                                {{ property.address|lower|truncatewords:"10" }}
                            </p>
                <p>Area: {{ property.area }} {{ property.units }}</p>
            </div>
        </div>
     {% endfor %}
    {% else %}
        <p>None to show!</p>
    {% endif %}

{% endblock %}

bbricks/templates/bbricks/logout.html
{% extends 'bbricks/base.html' %}

{% block content %}

    <h2>Logged out!</h2>
    <p>Click <a href="/bbricks/login/">here</a> to login again</p>

{% endblock %}

bbricks/templates/bbricks/pg.html
{% extends 'bbricks/base.html' %}

{% block sidebar %}
    <a class="nav-link" href="/bbricks/loggedin">Cancel</a>
{% endblock %}

{% block content %}

    <form action="/bbricks/pg/{{ property.id }}/" method="post">{% csrf_token %}
        {{ form.as_ul }}
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

{% endblock %}

bbricks/templates/bbricks/profile.html
{% extends 'bbricks/base.html' %}

{% block sidebar %}
            <a class="nav-link" href="/bbricks/loggedin/">Your Profile</a>
{% endblock %}

{% block content %}
    <ul>
    <p><img src="/static/assets/{{ user.userprofile.photo }}" width="200" /></p>
    <p>{{ user.first_name }} {{ user.last_name }}</p>
        <b>{{ user.userprofile.property_set.count }} properties</b>

        <div class="my-3 p-3 bg-white rounded box-shadow">
        <h2 class="border-bottom border-gray pb-2 mb-0">Properties</h2>
             {% if properties.count > 0 %}
                    {% for property in properties %}
                    <div class="media text-muted pt-3">
                      <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">

                        <div>
                            <h6><a href="/bbricks/get/{{ property.id }}/">{{ property.description }}</a></h6>
                            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                  <a href="/bbricks/profile/{{ user.username }}"><strong class="d-block text-gray-dark">@{{ user.username }}</strong></a>
                                {{ property.address|lower|truncatewords:"10" }}
                            </p>
                            <p>Price: {{ property.price }}</p>
                        </div>
                    </div>
                 {% endfor %}
                {% else %}
                    <p>None to show!</p>
                {% endif %}
        </div>

    </ul>


{% endblock %}